name: Plugin Build
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  buildmultijdk:
    if: (!startsWith(github.ref, 'refs/tags/'))
    needs: validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of some major Java version(s), as well as specific LTS version(s)
        java: [ 8, 11, 17 ]
    name: Gradle Build without Publish
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          java-package: jdk
      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
      - uses: gradle/gradle-build-action@v2.4.2
        id: gradle-cache
        with:
          gradle-version: release-candidate
      - name: Gradle build
        run: ./gradlew --stacktrace build
        env:
          JDK_VERSION_FOR_TESTS: ${{ matrix.java }}

